### ISSUE TITLE
[BGFIX] Wallpapers not applying to desktop, no issues in terminal

### ISSUE THREAD

**Issue by TeaJeep** [Almamu/linux-wallpaperengine#109]
**Desktop (please complete the following information):**
 
- OS: Arch Linux
 - Desktop Environment: XFCE
 - Window Manager: XFWM

**Additional context**

Wallpapers are rendering in a window, but not applying to the desktop.  The terminal output seems to be fine?  I do have the compositor disabled as well.  Might just be some mistake I'm making though?
![image](https://user-images.githubusercontent.com/63767429/174971341-6c6b4502-d686-477a-a51d-69dd557d9c14.png)

**Comment by RetroitKnife** [comment]
I am having the exact same issue here.

However what I've found out is that upon restart, while the wallpaper is being actively applied (like in the above screenshot), it showed up on the screen it was supposed to be applied very shortly. So it seems like it works, but not like intended.

- **Kernel:** 5.18.12-arch1-1
- **Driver:** nvidia 515.57-6
- **DE:** Plasma 5.25.3
- **WM:** KWin

**Comment by Almamu** [comment]
This looks to be DE-related. Desktop Environments usually like to draw their own background, so that's why you see a flash of it when you boot it up, because it takes some time until the DE re-draws it's background.

The only solution for now is either use a different DE or disable whatever app is drawing things on the background (this is usually the file explorer in use, and that might not be something you want to disable).

**Comment by Dezaku** [comment]
Found any solution? Im on XFCE too and the wallpapers just open as a window

**Comment by Almamu** [comment]
There's no support for Desktop Environments yet, only compositors like Picom which are mostly used for "ricing". The progress on this issue is tracked under #8.
