### ISSUE TITLE
[Question] Video

### ISSUE THREAD

**Issue by IceCryptonym** [Almamu/linux-wallpaperengine#13]
Right now there isn't a way to have videos played. I wanted to ask what we should use for the videos. As far as I know, there isn't a way to decode videos from SDL. Maybe we could use FFmpeg? 

This wallpaper uses a video:
https://steamcommunity.com/sharedfiles/filedetails/?id=894976291

**Comment by Almamu** [comment]
I didn't give it much though because these backgrounds are essentially a video that can be played thru mpv to the desktop.

Looking through the official information these are the supported formats: mp4, WebM, avi, m4v, mov, wmv (although only mp4 is uploaded to the steam workshop) so I'd say that ffmpeg is the best option to implement it, that way we don't need to extract the .pkg file temporarily for mpv or something else to read it.

**Comment by Almamu** [comment]
Work is being done on PR #14 by @IceCryptonym

**Comment by Almamu** [comment]
Video support without audio was implemented on PR #14 and merged into data-separation already, so this issue can be closed. Work on this will continue on issue #17 and #15
