### ISSUE TITLE
Implement support for audio on videos

### ISSUE THREAD

**Issue by Almamu** [Almamu/linux-wallpaperengine#17]
Video support was implemented on PR #14 without audio support. Next step would be to implement proper audio support so videos can play any kind of audio.

**Comment by Martin1995** [comment]
Is audio support already implemented?

I'm asking because I have two wallpapers that have a video file with audio that gets played back without audio.

[https://steamcommunity.com/sharedfiles/filedetails/?id=2172415034](url)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2227793928](url)

both have mp4 files directly in their folder.

**Comment by Almamu** [comment]
Audio support is only implemented for elements inside the background. Video backgrounds do not support audio playback yet, but will soon. Work being done on #83 should carry onto this feature too as the code should be pretty similar.

**Comment by Martin1995** [comment]
ok thank you for the info

**Comment by Almamu** [comment]
Proper video background playback with audio is added as of last commit and should work just fine. If you experience any issues please open a new issue so I can look into it.
