### ISSUE TITLE
terminate called after throwing an instance of 'nlohmann::detail::parse_error'

### ISSUE THREAD

**Issue by SBAPKat** [Almamu/linux-wallpaperengine#18]
I get this error with every wallpaper I try, so it's pretty unusable to me

`nexpected package header... Aborting load: /home/sbapkat/git/linux-wallpaperengine/build/2126043555/scene.pkg
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 18: syntax error - unexpected ':'; expected end of input
[1]    6418 abort (core dumped)  ./wallengine --pkg 2126043555`

**Comment by SBAPKat** [comment]
Note:
The command I use to start it is, for example ./wallengine --dir ./2107074398

**Comment by Almamu** [comment]
Looks like that background is using a more recent format for packaging. I've added the proper version to the check so that one should at least load and not crash, although I'm pretty sure It'll just display garbage on the master branch. The data separation branch won't load it because the support for particles and other things isn't completely implemented yet.

Take in mind that the project is pretty much in it's infancy right now, so not much works.

**Comment by SBAPKat** [comment]
It actually doesn't load, just crashes.
FYI, the same error occurs with --pkg and --dir even though it's a pkg background.
I'd be interested in participating in this project, but I don't think I have enough experience for that, sadly.

**Comment by Almamu** [comment]
Yeah sorry, forgot to push the change to the repo, this commit should get rid of the crash. The sound should play but the background will just display garbage: 39d3f4f1e096d0600ee088ca24f52bff149ae62f

The master branch is stalled because data-separation is where things are actually being developed for now, but It's still halfway done so everything either doesn't load or just displays a grey background, and It'll take some time for the project to be actually useful. It doesn't help that I don't have much time to dedicate to it.

**Comment by SBAPKat** [comment]
It now works, but doesn't actually display garbage. It does load the static part of the background.
It's already much better than before, thanks !

**Comment by Almamu** [comment]
Oh didn't expect that. I'll close the issue then ;)

**Comment by Martin1995** [comment]
I have the same problem, should i open a separate issue?

**Comment by Almamu** [comment]
> I have the same problem, should i open a separate issue?
@Martin1995 yes, open a new issue with the complete output of the command so I can help you.
