### ISSUE TITLE
Failed to open video file

### ISSUE THREAD

**Issue by JadeVane** [Almamu/linux-wallpaperengine#45]
I got this error when run a uncompressed wallpaper

```
./wallpaper --der /path/to/wallpaper
```

the error message here

```
Irrlicht Engine version 1.8.4
Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64
Using renderer: OpenGL 4.3
NV138: nouveau
OpenGL driver version is 1.2 or better.
GLSL version: 4.3
/home/wenjinyu/Pictures/1810612745/project.json
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open video file
```

Just 3 files there

- `.mp4`
- `git`: the preview of wallpaper
- `project.json`: with the content below

```
{
	"contentrating" : "Everyone",
	"description" : "原画来自P站画师Shell\nPixiv ID: 60886152\nMember: Shell\nhttps://www.pixiv.net/member_illust.php?mode=medium&illust_id=60886152",
	"file" : "魔法女孩2.mp4",
	"general" : 
	{
		"properties" : 
		{
			"schemecolor" : 
			{
				"order" : 0,
				"text" : "ui_browse_properties_scheme_color",
				"type" : "color",
				"value" : "0 0 0"
			}
		}
	},
	"preview" : "preview.gif",
	"tags" : [ "Anime" ],
	"title" : "魔女",
	"type" : "video",
	"visibility" : "public"
}
```

**Comment by Almamu** [comment]
Hmmmm could be encoding related. Can you check changing the "file" entry in the project.json to something that only has ascii characters and ensuring the mp4 file has the same name?

**Comment by Almamu** [comment]
That's weird, it should work without any modifications. I'll make a note of this and try to look into it later once I have some time to debug it.

Work on #8 is low on the priority list right now, mainly because the actual rendering of backgrounds is not really that advanced yet (and doesn't help that I've been having issues with Irrlicht to properly render everything in the background). It works without compositor for now, but until the rendering is more advanced I don't think It really matters If we can draw on the background or not (not to mention the amount of testing that would require each DE to ensure it renders properly on all of them).

**Comment by JadeVane** [comment]
I guess you are misunderstanding my words, I mean I changed the file name to what I like after copying the wallpaper from the wallpaper engine path of windows version which cause the error I have mentioned before, I just do what you said to get it work, so there is nothing to debug.

Actually, linux-wallpaperengine doesn't work after a series of configurations, it's not a wise choice to wait the change from DE, which mean that keeping the issue in this state, I can experience nothing now, so is there a way for the advanced user that change the configuration of DE to make wallpaper engine working now?

**Comment by Almamu** [comment]
> I guess you are misunderstanding my words, I mean I changed the file name to what I like after copying the wallpaper from the wallpaper engine path of windows version which cause the error I have mentioned before, I just do what you said to get it work, so there is nothing to debug.

Oh, okay.

> Actually, linux-wallpaperengine doesn't work after a series of configurations, it's not a wise choice to wait the change from DE, which mean that keeping the issue in this state, I can experience nothing now, so is there a way for the advanced user that change the configuration of DE to make wallpaper engine working now?

I am not waiting on any DE to make any changes. The issue lies with how advanced linux-wallpaperengine is, which is not much. Most of the things that it can render usually look bad (mainly because I'm still figuring out a lot of stuff of the original app), so I see no point in implementing anything advanced (to support DEs like Nautilus, KDE's or others) while the software itself is not that useful either. Supporting non-composited desktops is easy, because we can take full control over the main screen, so drawing on that is not that hard. But every DE does things in a different way, so I'd need to write custom code to support every one of them (and do some testing from time to time to ensure it works fine on all of them too) which would take me from the focus of getting a good rendering base laid out for the software. After more backgrounds start looking good I'll consider having the issue #8 as a higher priority issue so I can focus on implementing proper support for DEs and try to come up with a decent testing methodology so I don't need to run it manually on major DEs myself.

**Comment by Almamu** [comment]
I'll close this one for now as I don't see anything else you need help with. The support for other DEs is tracked on #8.
