### ISSUE TITLE
Error when try run

### ISSUE THREAD

**Issue by Vladsg** [Almamu/linux-wallpaperengine#51]
Maybe I'm doing something wrong, but when I try to run it shows an error 
![изображение](https://user-images.githubusercontent.com/19352528/132760407-1db289c0-0eab-4cad-ba0b-48f696ab1474.png)

**Comment by Almamu** [comment]
In this case you should be using the --pkg switch instead of --dir as there's just a project.json, a scene.pkg and the preview image.

**Comment by Vladsg** [comment]
I used both.Look at the terminal in the screenshot

**Comment by Vladsg** [comment]
if run in build folder
![изображение](https://user-images.githubusercontent.com/19352528/132761618-a777b2da-ff0b-411a-b9b0-6abd2eb9456e.png)

**Comment by Almamu** [comment]
Oh sorry, you're right, didn't notice the earlier runs of the command. I've looked into the background you're trying to run and seems to require support for things that are not implemented yet (audio processing, composite layers, etc) so that one won't load yet. I'm working on supporting those features as we speak, so it might still take me some time to get it properly supported, but there's other backgrounds that should work.
