### ISSUE TITLE
Same error on start with one exception across four wallpapers.

### ISSUE THREAD

**Issue by AleanaA** [Almamu/linux-wallpaperengine#58]
Across four wallpapers, one of which being the example used in the README, I wasn't able to get any of them working across two separate compilations of the application which appeared to have run without problem.
This makes me think I've missed something, but I'm not sure. The fourth wallpaper listed in the errors gave a unique error though, and I'm not sure how related the two errors are.

Currently on Arch/Garuda with the 5.15.3-zen1-1-zen kernel using a 3070 with Nvidia's proprietary drivers.

[CMake](https://pastebin.com/V2G09KyW)
[Make](https://pastebin.com/tBjuTspY)
```
--dir/--pkg is deprecated and not used anymore
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR PRE-COMPILING SHADERExpected type
zsh: abort (core dumped)  ./wallengine --pkg wallpapers/1845706469

--dir/--pkg is deprecated and not used anymore
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR PRE-COMPILING SHADERExpected type
zsh: abort (core dumped)  ./wallengine --pkg wallpapers/2125234447

--dir/--pkg is deprecated and not used anymore
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR PRE-COMPILING SHADERExpected type
zsh: abort (core dumped)  ./wallengine --pkg wallpapers/2173895465

--dir/--pkg is deprecated and not used anymore
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown shader constant type
zsh: abort (core dumped)  ./wallengine --pkg wallpapers/2022437634
```

**Comment by Almamu** [comment]
Hi @AleanaA 

I've uploaded some changes that should fix the issues you were having with the fourth background in the list (7db36183508a7057c91f8a7f244fb30cec837e04) so It should launch now (although there's an issue somewhere with shaders, so that one will be black until I can fix the issue). The other backgrounds should launch now since there were some issues with the default assets from wallpaper engine (they added new things to the code and the compiler wasn't too happy about them) on 9d2e9b43ee2eeb772ee65c0c9a8d72018ad62887. So the example background should work just fine again. The other backgrounds seem to still have some issues that I'm investigating.

**Comment by Almamu** [comment]
With the latest improvements these backgrounds should fare better. First, second and fourth I've tested and work just fine, nothing should prevent third from working too. Closing this for now. Feel free to re-open if they still don't look right (take into account that particles are not supported yet, progress on that is tracked under #52)
