### ISSUE TITLE
Is there a discord server/community 

### ISSUE THREAD

**Issue by Philipmikmik** [Almamu/linux-wallpaperengine#61]
As the question says. So we dont ask more general questions in the github issues?

**Comment by Almamu** [comment]
Hi @Philipmikmik 

Right now there's no community setup for the project, mainly because I don't have all the time I'd like to dedicate to the project. That and I don't really think much people is using it yet.

**Comment by Philipmikmik** [comment]
Thanks @Almamu , i have just one question. What is the thing not yet supported for [this](https://steamcommunity.com/sharedfiles/filedetails/?id=1744170047) 
![image](https://user-images.githubusercontent.com/65279994/144725757-6ff00825-7c13-4b5e-a1a9-53710a04d9e5.png)

**Comment by Almamu** [comment]
Those backgrounds require of a full-fledged web browser for them to work. It's something that I'm looking into implementing somewhat soon, but I cannot really guarantee when It'll be because there's some things to take into consideration first. If you find any web browser that can run as your desktop background you should be able to run it from the index.html just fine. But i'm not aware of any that support this kind of functionality.

**Comment by Philipmikmik** [comment]
Thanks, will look into it and if i cant find any, i will post it here

**Comment by Philipmikmik** [comment]
I found a plugin for Plasma KDE, [HTML Wallpaper](https://store.kde.org/p/1324580/), which works with showing the html but isnt customizable
