### ISSUE TITLE
[BUG] Asset folder cannot be found if not first cd into the directory

### ISSUE THREAD

**Issue by DashCruft** [Almamu/linux-wallpaperengine#82]
When I try to set the wallpaper without `cd` into the compiled directory, I keep getting the error that it can't find the asset folder, even though it already exists. My guess is that this is either a bug, or you'll need to implement a feature where we can set the path for the asset folder. Like a `--config` option maybe?

**Comment by Almamu** [comment]
I'm looking into this to come up with a good solution, due to how I've been running it I haven't found that issue yet myself, so it'll require some careful thinking first.

**Comment by DashCruft** [comment]
![image](https://user-images.githubusercontent.com/59381835/159348177-4d288f03-c1d4-4bff-9435-c1a20d708b80.png)

Here's an example.

**Comment by mihawk90** [comment]
On that note (not sure if I should open a separate issue/feature request for this :) ), it might be nice to have an alternate default location for the assets data, something like `~/.local/share/wallengine/assets`. This would certainly help with packaging since we obviously can't package the assets and asking users to copy stuff into a system directory after installation seems not-exactly-best-practice :)

It seems the assets dir is attempted to be found here:
https://github.com/Almamu/linux-wallpaperengine/blob/17d4be61b10b1fefb5eeeafe9111236947a69c85/main.cpp#L197-L198

And of course the Exception when it doesn't exist:
https://github.com/Almamu/linux-wallpaperengine/blob/17d4be61b10b1fefb5eeeafe9111236947a69c85/src/WallpaperEngine/Assets/CDirectory.cpp#L8-L15

I briefly looked at how OBS does this for plugins, but I didn't get very far. From what I can tell their cmake setup injects the install path into the pipeline somewhere? And then they just concatenate that with the plugin path(s):

https://github.com/obsproject/obs-studio/blob/737696950d770cdd6a677dac5c30cb1a34964daa/libobs/obs-nix.c#L56-L60

Although no idea where it loads user-installed plugins (i.e. `~/.config/obs-studio/plugins`) from.

**Comment by Almamu** [comment]
That's pretty much the approach I was going to take, provide some default path to use everywhere, including the default steam installation + an extra option to specify where the assets are. I have something already drafted, will try to finish it today

**Comment by mihawk90** [comment]
> including the default steam installation

That could be tricky as you won't necessarily know where the user put their steam library, but I guess at least using the `.local` steam path could work.
Maybe also take a look at Protontricks how they figure out where a game is installed :thinking:

**Comment by Almamu** [comment]
Most tools use a list of default paths that things can be at. I've added the most common steam paths (according to Protontricks) + a switch for changing where the assets folder is when the user has it's library somewhere else. I've also added extra checks for an assets folder in the same path as the binary is (instead of where you're running the binary) as fallback to keep a somewhat close implementation to what was happening before.

I'd mark this one as fixed, but if there's any other path I should include please open a new issue with the request.
